// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: party.proto

package net.runelite.client.party;

/* public */ final class Party {
  private Party() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface JoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Join)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * <pre>
   * c-&gt;s
   * </pre>
   *
   * Protobuf type {@code party.Join}
   */
  public  static final class Join extends
      com.google.protobuf.GeneratedMessageLite<
          Join, Join.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Join)
      JoinOrBuilder {
    private Join() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static Join parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Join parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Join parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Join parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Join parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Join parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Join parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Join parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Join parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Join parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Join parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Join parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Join prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * c-&gt;s
     * </pre>
     *
     * Protobuf type {@code party.Join}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Join, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Join)
        JoinOrBuilder {
      // Construct using net.runelite.client.party.Party.Join.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.Join)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Join();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "partyId_",
              "memberId_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Join> parser = PARSER;
          if (parser == null) {
            synchronized (Join.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Join>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Join)
    private static final Join DEFAULT_INSTANCE;
    static {
      Join defaultInstance = new Join();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Join.class, defaultInstance);
    }

    public static Join getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Join> PARSER;

    public static com.google.protobuf.Parser<Join> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Part)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code party.Part}
   */
  public  static final class Part extends
      com.google.protobuf.GeneratedMessageLite<
          Part, Part.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Part)
      PartOrBuilder {
    private Part() {
    }
    public static Part parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Part parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Part parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Part parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Part parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Part parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Part parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Part parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Part parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Part parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Part parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Part parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Part prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.Part}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Part, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Part)
        PartOrBuilder {
      // Construct using net.runelite.client.party.Party.Part.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:party.Part)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Part();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = null;
            String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Part> parser = PARSER;
          if (parser == null) {
            synchronized (Part.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Part>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Part)
    private static final Part DEFAULT_INSTANCE;
    static {
      Part defaultInstance = new Part();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Part.class, defaultInstance);
    }

    public static Part getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Part> PARSER;

    public static com.google.protobuf.Parser<Part> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code party.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:party.Data)
      DataOrBuilder {
    private Data() {
      type_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int TYPE_FIELD_NUMBER = 2;
    private String type_;
    /**
     * <code>string type = 2;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      return type_;
    }
    /**
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <code>string type = 2;</code>
     * @param value The type to set.
     */
    private void setType(
        String value) {
      Class<?> valueClass = value.getClass();
  
      type_ = value;
    }
    /**
     * <code>string type = 2;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 1;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 1;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Data prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.Data)
        DataOrBuilder {
      // Construct using net.runelite.client.party.Party.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string type = 2;</code>
       * @return The type.
       */
      @Override
      public String getType() {
        return instance.getType();
      }
      /**
       * <code>string type = 2;</code>
       * @return The bytes for type.
       */
      @Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <code>string type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.Data)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Data();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "data_",
              "type_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Data> parser = PARSER;
          if (parser == null) {
            synchronized (Data.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Data>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.Data)
    private static final Data DEFAULT_INSTANCE;
    static {
      Data defaultInstance = new Data();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Data.class, defaultInstance);
    }

    public static Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface C2SOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.C2S)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.party.Join join = 1;</code>
     * @return Whether the join field is set.
     */
    boolean hasJoin();
    /**
     * <code>.party.Join join = 1;</code>
     * @return The join.
     */
    Join getJoin();

    /**
     * <code>.party.Part part = 2;</code>
     * @return Whether the part field is set.
     */
    boolean hasPart();
    /**
     * <code>.party.Part part = 2;</code>
     * @return The part.
     */
    Part getPart();

    /**
     * <code>.party.Data data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.party.Data data = 3;</code>
     * @return The data.
     */
    Data getData();

    public C2S.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code party.C2S}
   */
  public  static final class C2S extends
      com.google.protobuf.GeneratedMessageLite<
          C2S, C2S.Builder> implements
      // @@protoc_insertion_point(message_implements:party.C2S)
      C2SOrBuilder {
    private C2S() {
    }
    private int msgCase_ = 0;
    private Object msg_;
    public enum MsgCase {
      JOIN(1),
      PART(2),
      DATA(3),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return JOIN;
          case 2: return PART;
          case 3: return DATA;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    private void clearMsg() {
      msgCase_ = 0;
      msg_ = null;
    }

    public static final int JOIN_FIELD_NUMBER = 1;
    /**
     * <code>.party.Join join = 1;</code>
     */
    @Override
    public boolean hasJoin() {
      return msgCase_ == 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    @Override
    public Join getJoin() {
      if (msgCase_ == 1) {
         return (Join) msg_;
      }
      return Join.getDefaultInstance();
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void setJoin(Join value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void mergeJoin(Join value) {
      value.getClass();
  if (msgCase_ == 1 &&
          msg_ != Join.getDefaultInstance()) {
        msg_ = Join.newBuilder((Join) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 1;
    }
    /**
     * <code>.party.Join join = 1;</code>
     */
    private void clearJoin() {
      if (msgCase_ == 1) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int PART_FIELD_NUMBER = 2;
    /**
     * <code>.party.Part part = 2;</code>
     */
    @Override
    public boolean hasPart() {
      return msgCase_ == 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    @Override
    public Part getPart() {
      if (msgCase_ == 2) {
         return (Part) msg_;
      }
      return Part.getDefaultInstance();
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void setPart(Part value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void mergePart(Part value) {
      value.getClass();
  if (msgCase_ == 2 &&
          msg_ != Part.getDefaultInstance()) {
        msg_ = Part.newBuilder((Part) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 2;
    }
    /**
     * <code>.party.Part part = 2;</code>
     */
    private void clearPart() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    /**
     * <code>.party.Data data = 3;</code>
     */
    @Override
    public boolean hasData() {
      return msgCase_ == 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    @Override
    public Data getData() {
      if (msgCase_ == 3) {
         return (Data) msg_;
      }
      return Data.getDefaultInstance();
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void setData(Data value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void mergeData(Data value) {
      value.getClass();
  if (msgCase_ == 3 &&
          msg_ != Data.getDefaultInstance()) {
        msg_ = Data.newBuilder((Data) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 3;
    }
    /**
     * <code>.party.Data data = 3;</code>
     */
    private void clearData() {
      if (msgCase_ == 3) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static C2S parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static C2S parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static C2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static C2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static C2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static C2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static C2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static C2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static C2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static C2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static C2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static C2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(C2S prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.C2S}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          C2S, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.C2S)
        C2SOrBuilder {
      // Construct using net.runelite.client.party.Party.C2S.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public MsgCase
          getMsgCase() {
        return instance.getMsgCase();
      }

      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }


      /**
       * <code>.party.Join join = 1;</code>
       */
      @Override
      public boolean hasJoin() {
        return instance.hasJoin();
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      @Override
      public Join getJoin() {
        return instance.getJoin();
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder setJoin(Join value) {
        copyOnWrite();
        instance.setJoin(value);
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder setJoin(
          Join.Builder builderForValue) {
        copyOnWrite();
        instance.setJoin(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder mergeJoin(Join value) {
        copyOnWrite();
        instance.mergeJoin(value);
        return this;
      }
      /**
       * <code>.party.Join join = 1;</code>
       */
      public Builder clearJoin() {
        copyOnWrite();
        instance.clearJoin();
        return this;
      }

      /**
       * <code>.party.Part part = 2;</code>
       */
      @Override
      public boolean hasPart() {
        return instance.hasPart();
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      @Override
      public Part getPart() {
        return instance.getPart();
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder setPart(Part value) {
        copyOnWrite();
        instance.setPart(value);
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder setPart(
          Part.Builder builderForValue) {
        copyOnWrite();
        instance.setPart(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder mergePart(Part value) {
        copyOnWrite();
        instance.mergePart(value);
        return this;
      }
      /**
       * <code>.party.Part part = 2;</code>
       */
      public Builder clearPart() {
        copyOnWrite();
        instance.clearPart();
        return this;
      }

      /**
       * <code>.party.Data data = 3;</code>
       */
      @Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      @Override
      public Data getData() {
        return instance.getData();
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder setData(Data value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder setData(
          Data.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder mergeData(Data value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.party.Data data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.C2S)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new C2S();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "msg_",
              "msgCase_",
              Join.class,
              Part.class,
              Data.class,
            };
            String info =
                "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001<\u0000\u0002<" +
                "\u0000\u0003<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<C2S> parser = PARSER;
          if (parser == null) {
            synchronized (C2S.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<C2S>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.C2S)
    private static final C2S DEFAULT_INSTANCE;
    static {
      C2S defaultInstance = new C2S();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        C2S.class, defaultInstance);
    }

    public static C2S getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<C2S> PARSER;

    public static com.google.protobuf.Parser<C2S> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserJoinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.UserJoin)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * <pre>
   * s-&gt;c
   * </pre>
   *
   * Protobuf type {@code party.UserJoin}
   */
  public  static final class UserJoin extends
      com.google.protobuf.GeneratedMessageLite<
          UserJoin, UserJoin.Builder> implements
      // @@protoc_insertion_point(message_implements:party.UserJoin)
      UserJoinOrBuilder {
    private UserJoin() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static UserJoin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserJoin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserJoin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserJoin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserJoin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserJoin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserJoin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserJoin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserJoin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UserJoin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserJoin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserJoin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UserJoin prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * s-&gt;c
     * </pre>
     *
     * Protobuf type {@code party.UserJoin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UserJoin, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.UserJoin)
        UserJoinOrBuilder {
      // Construct using net.runelite.client.party.Party.UserJoin.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.UserJoin)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UserJoin();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "partyId_",
              "memberId_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UserJoin> parser = PARSER;
          if (parser == null) {
            synchronized (UserJoin.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UserJoin>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.UserJoin)
    private static final UserJoin DEFAULT_INSTANCE;
    static {
      UserJoin defaultInstance = new UserJoin();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserJoin.class, defaultInstance);
    }

    public static UserJoin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserJoin> PARSER;

    public static com.google.protobuf.Parser<UserJoin> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserPartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.UserPart)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();
  }
  /**
   * Protobuf type {@code party.UserPart}
   */
  public  static final class UserPart extends
      com.google.protobuf.GeneratedMessageLite<
          UserPart, UserPart.Builder> implements
      // @@protoc_insertion_point(message_implements:party.UserPart)
      UserPartOrBuilder {
    private UserPart() {
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static UserPart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserPart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static UserPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static UserPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static UserPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static UserPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static UserPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(UserPart prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.UserPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          UserPart, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.UserPart)
        UserPartOrBuilder {
      // Construct using net.runelite.client.party.Party.UserPart.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.UserPart)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new UserPart();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "partyId_",
              "memberId_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<UserPart> parser = PARSER;
          if (parser == null) {
            synchronized (UserPart.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<UserPart>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.UserPart)
    private static final UserPart DEFAULT_INSTANCE;
    static {
      UserPart defaultInstance = new UserPart();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        UserPart.class, defaultInstance);
    }

    public static UserPart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserPart> PARSER;

    public static com.google.protobuf.Parser<UserPart> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PartyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.PartyData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    long getPartyId();

    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    long getMemberId();

    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    String getType();
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code party.PartyData}
   */
  public  static final class PartyData extends
      com.google.protobuf.GeneratedMessageLite<
          PartyData, PartyData.Builder> implements
      // @@protoc_insertion_point(message_implements:party.PartyData)
      PartyDataOrBuilder {
    private PartyData() {
      type_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int PARTYID_FIELD_NUMBER = 1;
    private long partyId_;
    /**
     * <code>int64 partyId = 1;</code>
     * @return The partyId.
     */
    @Override
    public long getPartyId() {
      return partyId_;
    }
    /**
     * <code>int64 partyId = 1;</code>
     * @param value The partyId to set.
     */
    private void setPartyId(long value) {
      
      partyId_ = value;
    }
    /**
     * <code>int64 partyId = 1;</code>
     */
    private void clearPartyId() {
      
      partyId_ = 0L;
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private long memberId_;
    /**
     * <code>int64 memberId = 2;</code>
     * @return The memberId.
     */
    @Override
    public long getMemberId() {
      return memberId_;
    }
    /**
     * <code>int64 memberId = 2;</code>
     * @param value The memberId to set.
     */
    private void setMemberId(long value) {
      
      memberId_ = value;
    }
    /**
     * <code>int64 memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = 0L;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private String type_;
    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      return type_;
    }
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <code>string type = 4;</code>
     * @param value The type to set.
     */
    private void setType(
        String value) {
      Class<?> valueClass = value.getClass();
  
      type_ = value;
    }
    /**
     * <code>string type = 4;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <code>string type = 4;</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 3;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 3;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <code>bytes data = 3;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static PartyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PartyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PartyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PartyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PartyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static PartyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static PartyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PartyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PartyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static PartyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static PartyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static PartyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(PartyData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.PartyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          PartyData, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.PartyData)
        PartyDataOrBuilder {
      // Construct using net.runelite.client.party.Party.PartyData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 partyId = 1;</code>
       * @return The partyId.
       */
      @Override
      public long getPartyId() {
        return instance.getPartyId();
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @param value The partyId to set.
       * @return This builder for chaining.
       */
      public Builder setPartyId(long value) {
        copyOnWrite();
        instance.setPartyId(value);
        return this;
      }
      /**
       * <code>int64 partyId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartyId() {
        copyOnWrite();
        instance.clearPartyId();
        return this;
      }

      /**
       * <code>int64 memberId = 2;</code>
       * @return The memberId.
       */
      @Override
      public long getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @param value The memberId to set.
       * @return This builder for chaining.
       */
      public Builder setMemberId(long value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>int64 memberId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }

      /**
       * <code>string type = 4;</code>
       * @return The type.
       */
      @Override
      public String getType() {
        return instance.getType();
      }
      /**
       * <code>string type = 4;</code>
       * @return The bytes for type.
       */
      @Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <code>string type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>string type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <code>string type = 4;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <code>bytes data = 3;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <code>bytes data = 3;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>bytes data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.PartyData)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new PartyData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "partyId_",
              "memberId_",
              "data_",
              "type_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0002\u0002\u0002" +
                "\u0003\n\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<PartyData> parser = PARSER;
          if (parser == null) {
            synchronized (PartyData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<PartyData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.PartyData)
    private static final PartyData DEFAULT_INSTANCE;
    static {
      PartyData defaultInstance = new PartyData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PartyData.class, defaultInstance);
    }

    public static PartyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PartyData> PARSER;

    public static com.google.protobuf.Parser<PartyData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:party.S2C)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.party.UserJoin join = 1;</code>
     * @return Whether the join field is set.
     */
    boolean hasJoin();
    /**
     * <code>.party.UserJoin join = 1;</code>
     * @return The join.
     */
    UserJoin getJoin();

    /**
     * <code>.party.UserPart part = 2;</code>
     * @return Whether the part field is set.
     */
    boolean hasPart();
    /**
     * <code>.party.UserPart part = 2;</code>
     * @return The part.
     */
    UserPart getPart();

    /**
     * <code>.party.PartyData data = 3;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.party.PartyData data = 3;</code>
     * @return The data.
     */
    PartyData getData();

    public S2C.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code party.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageLite<
          S2C, S2C.Builder> implements
      // @@protoc_insertion_point(message_implements:party.S2C)
      S2COrBuilder {
    private S2C() {
    }
    private int msgCase_ = 0;
    private Object msg_;
    public enum MsgCase {
      JOIN(1),
      PART(2),
      DATA(3),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return JOIN;
          case 2: return PART;
          case 3: return DATA;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    private void clearMsg() {
      msgCase_ = 0;
      msg_ = null;
    }

    public static final int JOIN_FIELD_NUMBER = 1;
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    @Override
    public boolean hasJoin() {
      return msgCase_ == 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    @Override
    public UserJoin getJoin() {
      if (msgCase_ == 1) {
         return (UserJoin) msg_;
      }
      return UserJoin.getDefaultInstance();
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void setJoin(UserJoin value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void mergeJoin(UserJoin value) {
      value.getClass();
  if (msgCase_ == 1 &&
          msg_ != UserJoin.getDefaultInstance()) {
        msg_ = UserJoin.newBuilder((UserJoin) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 1;
    }
    /**
     * <code>.party.UserJoin join = 1;</code>
     */
    private void clearJoin() {
      if (msgCase_ == 1) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int PART_FIELD_NUMBER = 2;
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    @Override
    public boolean hasPart() {
      return msgCase_ == 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    @Override
    public UserPart getPart() {
      if (msgCase_ == 2) {
         return (UserPart) msg_;
      }
      return UserPart.getDefaultInstance();
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void setPart(UserPart value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void mergePart(UserPart value) {
      value.getClass();
  if (msgCase_ == 2 &&
          msg_ != UserPart.getDefaultInstance()) {
        msg_ = UserPart.newBuilder((UserPart) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 2;
    }
    /**
     * <code>.party.UserPart part = 2;</code>
     */
    private void clearPart() {
      if (msgCase_ == 2) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    @Override
    public boolean hasData() {
      return msgCase_ == 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    @Override
    public PartyData getData() {
      if (msgCase_ == 3) {
         return (PartyData) msg_;
      }
      return PartyData.getDefaultInstance();
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void setData(PartyData value) {
      value.getClass();
  msg_ = value;
      msgCase_ = 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void mergeData(PartyData value) {
      value.getClass();
  if (msgCase_ == 3 &&
          msg_ != PartyData.getDefaultInstance()) {
        msg_ = PartyData.newBuilder((PartyData) msg_)
            .mergeFrom(value).buildPartial();
      } else {
        msg_ = value;
      }
      msgCase_ = 3;
    }
    /**
     * <code>.party.PartyData data = 3;</code>
     */
    private void clearData() {
      if (msgCase_ == 3) {
        msgCase_ = 0;
        msg_ = null;
      }
    }

    public static S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(S2C prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code party.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          S2C, Builder> implements
        // @@protoc_insertion_point(builder_implements:party.S2C)
        S2COrBuilder {
      // Construct using net.runelite.client.party.Party.S2C.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public MsgCase
          getMsgCase() {
        return instance.getMsgCase();
      }

      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }


      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      @Override
      public boolean hasJoin() {
        return instance.hasJoin();
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      @Override
      public UserJoin getJoin() {
        return instance.getJoin();
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder setJoin(UserJoin value) {
        copyOnWrite();
        instance.setJoin(value);
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder setJoin(
          UserJoin.Builder builderForValue) {
        copyOnWrite();
        instance.setJoin(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder mergeJoin(UserJoin value) {
        copyOnWrite();
        instance.mergeJoin(value);
        return this;
      }
      /**
       * <code>.party.UserJoin join = 1;</code>
       */
      public Builder clearJoin() {
        copyOnWrite();
        instance.clearJoin();
        return this;
      }

      /**
       * <code>.party.UserPart part = 2;</code>
       */
      @Override
      public boolean hasPart() {
        return instance.hasPart();
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      @Override
      public UserPart getPart() {
        return instance.getPart();
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder setPart(UserPart value) {
        copyOnWrite();
        instance.setPart(value);
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder setPart(
          UserPart.Builder builderForValue) {
        copyOnWrite();
        instance.setPart(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder mergePart(UserPart value) {
        copyOnWrite();
        instance.mergePart(value);
        return this;
      }
      /**
       * <code>.party.UserPart part = 2;</code>
       */
      public Builder clearPart() {
        copyOnWrite();
        instance.clearPart();
        return this;
      }

      /**
       * <code>.party.PartyData data = 3;</code>
       */
      @Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      @Override
      public PartyData getData() {
        return instance.getData();
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder setData(PartyData value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder setData(
          PartyData.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder mergeData(PartyData value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.party.PartyData data = 3;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:party.S2C)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new S2C();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "msg_",
              "msgCase_",
              UserJoin.class,
              UserPart.class,
              PartyData.class,
            };
            String info =
                "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001<\u0000\u0002<" +
                "\u0000\u0003<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<S2C> parser = PARSER;
          if (parser == null) {
            synchronized (S2C.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<S2C>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:party.S2C)
    private static final S2C DEFAULT_INSTANCE;
    static {
      S2C defaultInstance = new S2C();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        S2C.class, defaultInstance);
    }

    public static S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<S2C> PARSER;

    public static com.google.protobuf.Parser<S2C> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
